# Generated by Django 5.0.4 on 2024-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_passedtesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='title',
            field=models.TextField(default='Тестовое задание к уроку <django.db.models.fields.related.ForeignKey>', verbose_name='Название'),
        ),
    ]
