# Generated by Django 5.0.4 on 2024-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_testing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='title',
            field=models.TextField(default='Тестовое задание к уроку', verbose_name='Название'),
        ),
    ]
